# Generated by Django 5.2.7 on 2025-10-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='comments',
            field=models.ManyToManyField(blank=True, to='core.comment'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.like'),
        ),
    ]
